"""Core package for the simple Spider Solitaire project."""

from .cli import run_cli
from .engine import (
    CARDS_PER_RANK,
    COMPLETE_SEQUENCE_LENGTH,
    INITIAL_COLUMN_SIZES,
    NUM_COLUMNS,
    ONE_SUIT,
    WIN_COMPLETED_SEQUENCES,
    Card,
    GameState,
    GameStatus,
    Move,
    MoveResult,
    Rank,
    apply_move,
    create_deck,
    deal_stock,
    get_game_status,
    new_game,
    remove_complete_sequences,
    validate_move,
)

__all__ = [
    "CARDS_PER_RANK",
    "COMPLETE_SEQUENCE_LENGTH",
    "INITIAL_COLUMN_SIZES",
    "NUM_COLUMNS",
    "ONE_SUIT",
    "WIN_COMPLETED_SEQUENCES",
    "Card",
    "GameStatus",
    "GameState",
    "Move",
    "MoveResult",
    "Rank",
    "apply_move",
    "create_deck",
    "deal_stock",
    "get_game_status",
    "new_game",
    "remove_complete_sequences",
    "validate_move",
    "run_cli",
]
